### ISSUE TITLE
images

### ISSUE THREAD

**Issue by sherinann** [sherinann/tic-tac-toe#1]
![screenshot1](https://user-images.githubusercontent.com/13931506/27763774-d9f519f0-5ea7-11e7-9b71-2d47a78f517e.png)

**Comment by ParadoxZero** [comment]
what's wrong?

**Comment by sherinann** [comment]
i saw this answer on how to add images to readme
that involved issues

**Comment by ParadoxZero** [comment]
Oh, for that, you don't actually need add the issue. Just copy the markdown it generated when you drag and drop image. and paste it into readme.

**Comment by sherinann** [comment]
tried
